openapi: "3.0.0"
info:
  version: 1.0.0
  title: ByteKeeper
  license:
    name: MIT
servers:
  - url: http://localhost:8080

paths:
  /getByteFile:
    post:
      summary: Get a ByteFile
      operationId: getByteFile
      tags:
        - ByteKeeper
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetByteFileRequest"
      responses:
        200:
          description: ByteFile retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetByteFileResponse"
        400:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /getByteFiles:
    post:
      summary: Get multiple ByteFiles
      operationId: getByteFiles
      tags:
        - ByteKeeper
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetByteFilesRequest"
      responses:
        200:
          description: Files retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetByteFilesResponse"
        400:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /download/{id}:
    get:
      summary: Download a file
      operationId: downloadFile
      tags:
        - ByteKeeper
      parameters:
        - in: path
          name: id
          schema:
            type: string
          required: true
          description: Identifier of file
      responses:
        200:
          description: File retrieved
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        400:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        404:
          description: File not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /putFile:
    post:
      summary: Put a file
      operationId: putFile
      tags:
        - ByteKeeper
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              properties:
                putFileRequest:
                  $ref: "#/components/schemas/PutFileRequest"
                file:
                  type: string
                  format: binary
              required:
                - file
      responses:
        200:
          description: File put
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutFileResponse"
        400:
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    GetByteFileRequest:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Identifier"
      required:
        - id
    GetByteFileResponse:
      type: object
      properties:
        byteFile:
          $ref: "#/components/schemas/ByteFile"
      required:
        - byteFile

    GetByteFilesRequest:
      type: object
      properties:
        ids:
          type: array
          items:
            $ref: "#/components/schemas/Identifier"
          minItems: 2
      required:
        - ids
    GetByteFilesResponse:
      type: object
      properties:
        byteFiles:
          type: array
          items:
            $ref: "#/components/schemas/ByteFile"
      required:
        - byteFiles

    PutFileRequest:
      type: object
      properties:
        meta:
          type: string
    PutFileResponse:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Identifier"
      required:
        - id

    ErrorResponse:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    ByteFile:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Identifier"
        name:
          type: string
        size:
          type: integer
          format: int64
        createdAt:
          type: integer
          format: int64
      required:
        - id

    Identifier:
      type: object
      properties:
        value:
          type: string
      required:
        - value
