openapi: "3.0.0"
info:
  version: 1.0.0
  title: ByteKeeper
  license:
    name: MIT

paths:
  /getFile:
    post:
      summary: Get a file
      operationId: getFile
      tags:
        - ByteKeeper
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetFileRequest"
      responses:
        200:
          description: File retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetFileResponse"
  /getFiles:
    post:
      summary: Get multiple files
      operationId: getFiles
      tags:
        - ByteKeeper
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GetFilesRequest"
      responses:
        200:
          description: Files retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetFilesResponse"
  /putFile:
    post:
      summary: Put a file
      operationId: putFile
      tags:
        - ByteKeeper
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PutFileRequest"
      responses:
        200:
          description: File put
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PutFileResponse"

components:
  schemas:
    GetFileRequest:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Identifier"
      required:
        - id
    GetFileResponse:
      type: object
      properties:
        byteFile:
          $ref: "#/components/schemas/ByteFile"
      required:
        - byteFile

    GetFilesRequest:
      type: object
      properties:
        ids:
          type: array
          items:
            $ref: "#/components/schemas/Identifier"
      required:
        - ids
    GetFilesResponse:
      type: object
      properties:
        byteFiles:
          type: array
          items:
            $ref: "#/components/schemas/ByteFile"
      required:
        - byteFiles

    PutFileRequest:
      type: object
      properties:
        byteFile:
          $ref: "#/components/schemas/ByteFile"
      required:
        - byteFile

    PutFileResponse:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Identifier"
      required:
        - id

    ByteFile:
      type: object
      properties:
        id:
          $ref: "#/components/schemas/Identifier"
        content:
          type: string
      required:
        - id

    Identifier:
      type: object
      properties:
        value:
          type: string
      required:
        - value
